name: deploy the node js app on the EC2


on:
   push:
    branches: 
        - main

jobs: 
    deploy:
        name: clone the repo
        runs-on: ubuntu-latest
        steps:
              - name: clone the repo
                uses: actions/checkout@v3
              
              - name: setup the node
                uses: actions/setup-node@v3
                with:
                  node-version: '18'

              - name: install the dependencies
                run: npm install
            
              - name: Add SSH Key
                run: |
                  echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
                  chmod 600 key.pem
              - name: Copy files to EC2
                run: |
                  rsync -avz -e "ssh -i key.pem -o StrictHostKeyChecking=no" ./ ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USERNAME }}/app
            
              - name: Restart app using PM2
                run: |
                  ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
                   cd /home/${{ secrets.EC2_USERNAME }}/app
                   /home/ubuntu/.nvm/versions/node/v18.20.8/bin/npm install
                   /home/ubuntu/.nvm/versions/node/v18.20.8/bin/pm2 restart app || /home/ubuntu/.nvm/versions/node/v18.20.8/bin/pm2 start index.js --name app
                  EOF
            
                
                

    