name: 'githubactions'

on:
  push:
    branches:
        - main

    
  


jobs:
    build:
        name: 'Clone The Repo First'
        runs-on: ubuntu-latest

        steps:
            - name: cloning the code
              uses: actions/checkout@v3

            - name: Add SSH Key
              run: |
               echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
               chmod 600 key.pem

            - name: Copy files to EC2
              run: |
                rsync -avz -e "ssh -i key.pem -o StrictHostKeyChecking=no" ./ ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USERNAME }}/app

            - name: Restart app using PM2
              run: |
                ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << EOF
                   cd /home/${{ secrets.EC2_USERNAME }}/app
                   docker stop profile || true
                   docker rm profile || true
                   docker build -t nodeapp .
                   docker run -d --name profile -p 9000:9000 nodeapp
                EOF
              
            
    